### ISSUE TITLE
after jooq v-3.10.0,there is index attribute in genenate

### ISSUE THREAD

**Issue by killthatbird** [etiennestuder/gradle-jooq-plugin#57] opened 2017-10-20 03:02 UTC
after jooq v-3.10.0,there is index attribute in genenate, the index attribute is not configurable at moment

**Comment by etiennestuder** [comment] 2017-10-20 15:44
Duplicate of https://github.com/etiennestuder/gradle-jooq-plugin/issues/58.

**Closed by etiennestuder** 2017-10-20 15:44 UTC
