### ISSUE TITLE
Missing JooqEdition

### ISSUE THREAD

**Issue by tomort** [etiennestuder/gradle-jooq-plugin#111] opened 2020-01-15 07:01 UTC
I'm working with Jooq 3.12.2 pro-java-8.
Missing the entry in the edition enum.
With 'PRO' the plugin did not work.
How can I fix that?

**Comment by etiennestuder** [comment] 2020-01-15 12:28
Please provide a detailed bug report incl. a reproducible example if you want your issue to be considered.

**Comment by etiennestuder** [comment] 2020-01-26 06:27
Closing since no further details were provided.

**Closed by etiennestuder** 2020-01-26 06:27 UTC
