### ISSUE TITLE
Unable to Override XSD Version to 3.18 for org.jooq.pro-java-11 with Java 11 Compatibility

### ISSUE THREAD

**Issue by ncheema** [etiennestuder/gradle-jooq-plugin#640] opened 2023-07-06 21:02 UTC
We are currently using version `3.18` of `org.jooq.pro-java-11`. However, we are facing difficulties in overriding the XSD version to 3.18 because it is not compatible with Java 11. We need suggestions on how to utilize the latest XSD version (3.18) with the pro-java-11 jar.

```
Java Version: Java 11
Gradle Jooq Plugin Version: 7.2
Jooq Version: 3.18.4

// config override 
buildscript {
    configurations["classpath"].resolutionStrategy.eachDependency {
        if (requested.group == "org.jooq") {
            useVersion("3.18.4")
        }
    }
}

```

### Error

```
Could not generate a decorated class for type JooqConfig.
   > org/jooq/meta/jaxb/Configuration has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

```

**Comment by lukaseder** [comment] 2023-07-07 14:32
The `groupId` is `org.jooq.pro-java-11`, not `org.jooq` (as in `requested.group`). Have you tried that? Also, did you specify the correct edition here?
https://github.com/etiennestuder/gradle-jooq-plugin#specifying-the-jooq-version-and-edition

**Comment by ncheema** [comment] 2023-07-10 21:11
overriding to `org.jooq.pro-java-11` didn't help. Plugin is still picking up `jooq-meta-3.16.12.jar` 
```kotlin
buildscript {
    configurations["classpath"].resolutionStrategy.eachDependency {
        if (requested.group == "org.jooq.pro-java-11") {
            useVersion("3.18.4")
        }
    }
}

jooq {
    version.set("3.18.4")
    edition.set(JooqEdition.PRO_JAVA_11)
    configurations {
        create("main") {
            ...
            // xsd used here is still 3.16.x
        }
    }
}
```

**Comment by lukaseder** [comment] 2023-07-12 09:14
I'll try to reproduce this.

Workarounds include:

- Use Java 17 to generate code instead of Java 11 (it shouldn't matter?)
- Use an older version of jOOQ to generate code. jOOQ 3.16 is still maintained, and unless you need access to a newer code generation feature, the older generated code should be compatible with newer runtime library versions.
- Use another mechanism than this third party plugin, including Maven or standalone code generation configuration (this plugin just calls through to the `GenerationTool` class, it provides glue code for better Gradle usage, but it isn't strictly necessary)

**Comment by lukaseder** [comment] 2023-07-12 09:35
I tried this against the example here:
https://github.com/etiennestuder/gradle-jooq-plugin/tree/main/example/specify_jooq_config_xml_schema_version

```patch
diff --git a/build.gradle b/build.gradle
index 598f706..81a867c 100644
--- a/build.gradle
+++ b/build.gradle
@@ -22,6 +22,8 @@ configurations.all { Configuration c ->
 
 dependencies {
     api 'org.jooq:jooq-codegen:3.18.4'
+    implementation project(path: ':')
+    implementation project(path: ':')
 
     runtimeOnly 'org.glassfish.jaxb:jaxb-core:3.0.2'
     runtimeOnly 'org.glassfish.jaxb:jaxb-runtime:3.0.2'
diff --git a/example/specify_jooq_config_xml_schema_version/build.gradle b/example/specify_jooq_config_xml_schema_version/build.gradle
index 9414995..2b22f76 100644
--- a/example/specify_jooq_config_xml_schema_version/build.gradle
+++ b/example/specify_jooq_config_xml_schema_version/build.gradle
@@ -1,18 +1,25 @@
 buildscript {
     configurations['classpath'].resolutionStrategy.eachDependency {
-        if (requested.group == 'org.jooq') {
+        if (requested.group == 'org.jooq.pro-java-11') {
             // set jOOQ version used at configuration time to enforce a specific jOOQ config XML schema version
-            useVersion '3.16.1'
+            useVersion '3.18.5'
         }
     }
 }
 
 plugins {
-    id 'nu.studer.jooq' version '8.2'
+    id 'nu.studer.jooq' version '7.2'
     id 'java'
 }
 
+java {
+    toolchain {
+        languageVersion = JavaLanguageVersion.of(11)
+    }
+}
+
 repositories {
+    mavenLocal()
     mavenCentral()
 }
 
@@ -21,7 +28,8 @@ dependencies {
 }
 
 jooq {
-    version = '3.16.1'
+    version = '3.18.5'
+    edition = nu.studer.gradle.jooq.JooqEdition.PRO_JAVA_11
 
     configurations {
         main {
```

It seems to work:

```
lukas@LAPTOP-VH130UJV MINGW64 ~/jOOQ/gradle/gradle-jooq-plugin/example/specify_jooq_config_xml_schema_version
$ java -version
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

lukas@LAPTOP-VH130UJV MINGW64 ~/jOOQ/gradle/gradle-jooq-plugin/example/specify_jooq_config_xml_schema_version
$ ./gradlew build
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8

> Task :generateJooq
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8

BUILD SUCCESSFUL in 5s
3 actionable tasks: 1 executed, 2 up-to-date
```

Am I missing some element to reproduce the problem you're having?

**Comment by lukaseder** [comment] 2023-07-12 09:39
> ```diff
> +    implementation project(path: ':')
> +    implementation project(path: ':')
> ```

Note this part was added by IntelliJ, I didn't add it consciously...

**Comment by lukaseder** [comment] 2023-07-12 09:43
OK, I get it. Adding a `forcedType` with a commercial feature like this does the trick:

```
forcedTypes {
    forcedType {
        auditUpdateUser = true
        name = 'int'
        includeExpression = 'dummy'
    }
}
```

Producing with `requested.group == 'org.jooq.pro-java-11'`:

```
lukas@LAPTOP-VH130UJV MINGW64 ~/jOOQ/gradle/gradle-jooq-plugin/example/specify_jooq_config_xml_schema_version
$ ./gradlew build
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\lukas\jOOQ\gradle\gradle-jooq-plugin\example\specify_jooq_config_xml_schema_version\build.gradle' line: 52

* What went wrong:
A problem occurred evaluating root project 'jooq-example-specify-jooq-config-xml-schema-version'.
> Invalid property: 'auditUpdateUser' on extension 'jooq.main.generationTool.generator.database.forcedTypes.forcedType', value: true. Please check the current XSD: https://www.jooq.org/xsd/jooq-codegen-3.16.5.xsd.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org
```

Or with `requested.group == 'org.jooq'`

```
lukas@LAPTOP-VH130UJV MINGW64 ~/jOOQ/gradle/gradle-jooq-plugin/example/specify_jooq_config_xml_schema_version
$ ./gradlew build
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\lukas\jOOQ\gradle\gradle-jooq-plugin\example\specify_jooq_config_xml_schema_version\build.gradle' line: 35

* What went wrong:
A problem occurred evaluating root project 'jooq-example-specify-jooq-config-xml-schema-version'.
> Could not create an instance of type nu.studer.gradle.jooq.JooqConfig.
   > Could not generate a decorated class for type JooqConfig.
      > org/jooq/meta/jaxb/Configuration has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

**Comment by lukaseder** [comment] 2023-07-12 09:59
Debugging:

```
buildscript {
    configurations['classpath'].resolutionStrategy.eachDependency {
        println(requested)
        if (requested.group == 'org.jooq') {
            // set jOOQ version used at configuration time to enforce a specific jOOQ config XML schema version
            useVersion '3.18.5'
        }
    }
}
```

The println produces:

```
lukas@LAPTOP-VH130UJV MINGW64 ~/jOOQ/gradle/gradle-jooq-plugin/example/specify_jooq_config_xml_schema_version
$ ./gradlew build
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8

> Configure project :
nu.studer.jooq:nu.studer.jooq.gradle.plugin:7.2
org.apache.logging.log4j:log4j-core:2.17.1
nu.studer:gradle-jooq-plugin:7.2
org.jooq:jooq-codegen:3.16.12
org.glassfish.jaxb:jaxb-core:3.0.2
org.glassfish.jaxb:jaxb-runtime:3.0.2
org.jooq:jooq:3.18.5
org.jooq:jooq-meta:3.18.5
jakarta.xml.bind:jakarta.xml.bind-api:3.0.1
com.sun.activation:jakarta.activation:2.0.1
org.glassfish.jaxb:txw2:3.0.2
com.sun.istack:istack-commons-runtime:4.0.1
io.r2dbc:r2dbc-spi:1.0.0.RELEASE
jakarta.xml.bind:jakarta.xml.bind-api:3.0.0
org.reactivestreams:reactive-streams:1.0.3
```

So, the `groupId` is wrong here (also the `jooq-codegen` version isn't patched!). Perhaps there's a flaw in `JooqPlugin`, which hardcodes some `groupIds`. I've created an issue and will check if it does solve the problem:

- https://github.com/etiennestuder/gradle-jooq-plugin/issues/643

**Comment by lukaseder** [comment] 2023-07-12 10:24
I'm not sure if there's going to be a solution to this problem, going forward. Since this plugin is compiled against the jOOQ Open Source Edition, which has a baseline of Java 17, it had to follow suit in its own compilation, so the plugin itself requires Java 17.

There's a much requested task to create an official gradle plugin offered by jOOQ, which would take care of these versioning problems:

- https://github.com/jOOQ/jOOQ/issues/12985

Other than that, it seems that these cases simply won't be supported by this third party plugin? What's your take on this, @etiennestuder ? Can you make an official statement and put this in the readme, perhaps? I understand that an increasing number of jOOQ customers will run into this limitation, where the workarounds are any of the ones I listed above:

- https://github.com/etiennestuder/gradle-jooq-plugin/issues/640#issuecomment-1632144809

Including using Java 17 for code generation or not using this plugin here.

**Comment by lukaseder** [comment] 2023-07-13 12:34
Well, https://github.com/jOOQ/jOOQ/issues/12985 will definitely ship in jOOQ 3.19, possibly with backports to older releases including 3.18.6, 3.17.15, 3.16.21. With this, the versioning troubles will be a thing of the past.

You can follow updates on https://github.com/jOOQ/jOOQ/issues/12985.

**Comment by etiennestuder** [comment] 2023-12-26 11:26
@ncheema @lukaseder

> Since this plugin is compiled against the jOOQ Open Source Edition, which has a baseline of Java 17, it had to follow suit in its own compilation, so the plugin itself requires Java 17.

The above statement from Lukas is correct. Hence, since the gradle-jooq-plugin needs to be compiled with Java 17, the Java runtime used to run the Gradle build requires Java 17, too.

But... note that you can run the actual code generation task with Java 11 since the `JooqGenerate` Gradle task supports the Gradle Toolchain feature. There is a full example [here](https://github.com/etiennestuder/gradle-jooq-plugin/blob/main/example/configure_toolchain_gradle_dsl/build.gradle). You can find more info on the Gradle Toolchain feature in the [Gradle docs](https://docs.gradle.org/current/userguide/toolchains.html)

The following should work:
- use the latest gradle-jooq-plugin 3.8.2
- define 3.18 and org.jooq.pro-java-11 as the version and edition in the build script's jOOQ configuration
- define Java 11 as the toolchain to use on the `JoogGenerate` task, as shown in the [example](https://github.com/etiennestuder/gradle-jooq-plugin/blob/main/example/configure_toolchain_gradle_dsl/build.gradle)
- define Java 11 as the toolchain to compile the generated sources, as shown in the same example
- run the Gradle build with Java runtime 17

**Closed by etiennestuder** 2023-12-26 11:26 UTC
