### ISSUE TITLE
Jooq Gradle plugin fails with Java 9 

### ISSUE THREAD

**Issue by relgames** [etiennestuder/gradle-jooq-plugin#55] opened 2017-09-23 14:41 UTC
### Steps to reproduce the problem:
Run Gradle plugin with Java 9, task "generate"

### Versions:
- jOOQ: 3.9.5
- plugin: 'nu.studer.jooq' version '2.0.7'
- Database (include vendor): postgres

```
> Task :generateJooqSchemaSource
Error: Unable to initialize main class org.jooq.util.GenerationTool
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/ValidationEventHandler
```

**Comment by lukaseder** [comment] 2017-09-23 17:53
Probably the same issue as this one: https://github.com/jOOQ/jOOQ/issues/6477
Can you confirm?

**Comment by relgames** [comment] 2017-09-25 12:04
Yes, looks same. But I have no idea how to pass `--add-modules` to jooq Gradle plugin.

**Comment by lukaseder** [comment] 2017-10-04 11:01
@etiennestuder Any ideas? How does Gradle work with Java 9, when plugins have a JAXB dependency?

**Comment by etiennestuder** [comment] 2017-10-20 15:47
@lukaseder I don't know right now. I will have to investigate (or someone else does before me).

**Comment by lukaseder** [comment] 2017-10-30 10:34
@etiennestuder: We need to get the `--add-modules java.xml.bind` JVM argument on the JVM that runs the jOOQ code generation. I must say, from the docs here: https://guides.gradle.org/building-java-9-modules, I'm not sure how this should be done. In Maven, there's a global `MAVEN_OPTS` setting, which is of course an unclean workaround. Does something like this exist in Gradle?

**Comment by etiennestuder** [comment] 2017-10-30 10:38
@lukaseder I'll look into it. I have not been in touch with Gradle / Java 9, yet.

**Comment by lukaseder** [comment] 2017-10-30 10:41
@etiennestuder It's a mess (not Gradle related). As long as we're in the transition phase where libraries aren't modularised yet, things are really tricky to tackle... :( So, the global "unclean" workaround might often be the best choice, if it exists.

**Comment by etiennestuder** [comment] 2017-10-30 10:42
@ldaley I'll see if I can provide a generic config options for JVM options.

**Comment by ldaley** [comment] 2017-10-30 10:43
@etiennestuder wrong `Luk*` :)

**Comment by etiennestuder** [comment] 2017-10-30 10:44
Oops....

**Comment by etiennestuder** [comment] 2017-10-30 16:35
@lukaseder @relgames You can already pass JVM args to the process running jOOQ, as demonstrated [here](https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/add_jvm_args/build.gradle#L46).

**Comment by etiennestuder** [comment] 2017-10-31 16:35
I'm going to close this issue since there is a way to make this work with Java 9. See https://github.com/etiennestuder/gradle-jooq-plugin/issues/55#issuecomment-340503912.

**Closed** 2017-10-31 16:35 UTC

**Comment by relgames** [comment] 2017-12-03 23:24
Thanks, indeed, it worked:
```groovy
tasks.generateMyProjectJooqSchemaSource.with {
    javaExecSpec = { JavaExecSpec s ->
        s.jvmArgs '--add-modules', 'java.xml.bind'
    }
}
```
Also I had to disable `@Generated` annotation with `generatedAnnotation = false`

**Comment by wieki** [comment] 2017-12-14 20:18
I've tried to use the extra tasks with Java 9 and the Gradle plug in, but the exception for the missing JAXB validator persists. Are there any other additions necessary to get this running?

**Comment by etiennestuder** [comment] 2017-12-15 05:10
I'm not familiar with jOOQ on Java 9. Maybe @relgames or @lukaseder have more ideas to help you out.

**Comment by lukaseder** [comment] 2017-12-15 08:17
@wieki: Can you provide an [mcve](https://stackoverflow.com/help/mcve)?

**Comment by wieki** [comment] 2017-12-15 08:25
Certainly, I've attached my tiny test project.

[device_service.tar.gz](https://github.com/etiennestuder/gradle-jooq-plugin/files/1562036/device_service.tar.gz)

**Comment by wieki** [comment] 2017-12-15 10:00
The problem was apparently not with the project and task, but a problem with Intellij, an upgrade to the latest build of the IDE now ends up in a successful build.

**Comment by lukaseder** [comment] 2017-12-15 14:55
Thanks @wieki. I've received an email with this deleted comment of yours:

> The problem was apparently not with the project and task, but a problem with Intellij, an upgrade to the latest build of the IDE now ends up in a successful build.

Does it work for you now, or was that a false positive?

**Comment by wieki** [comment] 2017-12-15 15:45
It was a false positive, I realized it just after submitting the comment.

**Comment by relgames** [comment] 2017-12-15 17:46
@wieki try to also add `gradle.properties` file with the following content:
```
org.gradle.jvmargs=--add-modules java.corba,java.xml.bind

```

**Comment by wieki** [comment] 2017-12-19 08:16
@relgames Thank you for you reply, I can confirm that by adding the gradle.properties to the project the project build and generates the expected files.

**Comment by lukaseder** [comment] 2017-12-19 08:34
@relgames How did corba slip in here? Is that really required for jOOQ (how so), or do you have other dependencies on your project?

**Comment by wieki** [comment] 2017-12-19 08:55
@lukaseder There is no need to included the java.corba modules as far as I can see, the build and generation process works well without the corba module.

**Comment by lukaseder** [comment] 2017-12-19 08:59
Whew, I'm glad there's no such hidden ugliness in jOOQ :-)

**Comment by relgames** [comment] 2017-12-19 10:26
@lukaseder I copy-pasted from my other project, indeed it's not needed for jOOQ :)

**Comment by 0x6e6562** [comment] 2018-03-28 09:29
In addition to the `gradle.properties` suggestion from @relgames, I also added this to the dependencies section:

```
dependencies {
    compile "org.jooq:jooq:$jooqVersion"
    jooqRuntime "com.sun.activation:javax.activation:1.2.0"
    jooqRuntime "org.glassfish.jaxb:jaxb-runtime:2.2.11"
}
```

This seems to work on 9 and 10, but 10 complains about illegal reflective access. Not sure where this is problem or not.

Does JOOQ work on 10 BTW?

**Comment by lukaseder** [comment] 2018-03-28 10:40
> Does JOOQ work on 10 BTW?

Yes, in principle. Please report bugs to : https://github.com/jOOQ/jOOQ/issues/new (if unrelated to this gradle plugin)

**Comment by CarrotCodes** [comment] 2018-04-24 20:47
Got here from Googling around a very similar exception, running the generator/plugin on Java 9/10: `java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory`

I couldn't get the `gradle.properties` addition working, and configuration of this plugin with Kotlin DSL is really hard, so I couldn't figure out adding the JVM additions in there either.

I did, however, get this working in the terminal: `./gradlew aggregator:generateJooq -Dorg.gradle.jvmargs="--add-modules java.xml.bind"` where `aggregator` is a subproject of mine, and `generateJooq` is a task I've added to do the generation manually when needed.
