### ISSUE TITLE
Mark generated directory as being builtBy jooq

### ISSUE THREAD

**Issue by NikolayMetchev** [etiennestuder/gradle-jooq-plugin#170] opened 2021-04-14 20:41 UTC
I originally posted this in the Gradle slack channel here:
https://gradle-community.slack.com/archives/CAHSN3LDN/p1618304400230700

It seems that if you use the Jooq gradle plugin in conjunction with kotlin annotation processing Gradle gives the following error message:
```
Execution optimizations have been disabled for task ':swift-service:kaptGenerateStubsKotlin' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/ntmetchev/Paxos/dev/metals/swift-service/build/generated-src/jooq/main'. Reason: Task ':swift-service:kaptGenerateStubsKotlin' uses this output of task ':swift-service:generateJooq' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

In the Gradle slack channel it was suggested that this could be addressed by modifying this line:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/src/main/groovy/nu/studer/gradle/jooq/JooqPlugin.java#L54
and marking the directory as `builtBy(jooq)`

The current workaround for me is to have the following in my build script:
```
tasks.matching { it.name == "kaptGenerateStubsKotlin" }.configureEach { it.dependsOn "generateJooq" }
```

This is with Gradle 7.0 and jooq 3.14.8 and plugin version 5.2.1

**Comment by etiennestuder** [comment] 2021-04-16 08:30
Thanks for the report. I don't think the problem lies in the jooq plugin, but in how the `kaptGenerateStubsKotlin` is configured to consume the output of the jooq task. I'm not 100% certain though sinice I'm not familiar with kapt.

**Comment by etiennestuder** [comment] 2021-04-16 08:37
@NikolayMetchev do you have `generateSchemaSourceOnCompilation` disabled?

**Comment by NikolayMetchev** [comment] 2021-04-16 11:09
@etiennestuder I haven't specified that flag. I presume `apt` will have a similar problem to `kapt`. Do you need me to try and create a small case to reproduce?

**Comment by etiennestuder** [comment] 2021-04-16 12:09
> Do you need me to try and create a small case to reproduce?
@NikolayMetchev that would be great. A test case in JooqFuncTest would be gold :-) But a self-contained build.gradle reproducer will also do it.

This will make it easier for me to raise it with our Gradle Build Tool team.

**Comment by NikolayMetchev** [comment] 2021-04-16 22:00
Using Gradle 7.0 and this `build.gradle.kts` the problem reproduces:

```
import org.gradle.api.tasks.PathSensitivity.RELATIVE
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

buildscript {
  dependencies {
    classpath("io.zonky.test:embedded-postgres:1.2.10")
  }
}

plugins {
  kotlin("jvm") version "1.4.32"
  kotlin("kapt") version "1.4.32"
  id("nu.studer.jooq") version "5.2.1"
}

group = "bug"
version = "1.0-SNAPSHOT"

repositories {
  mavenCentral()
}

tasks.withType<KotlinCompile>() {
  kotlinOptions.jvmTarget = "11"
}

val server =

jooq {
  version.set("3.14.8")
  configurations {
    create("main") {
      jooqConfiguration.apply {
        jdbc.apply {
          url = "jdbc:postgresql://localhost:55555/postgres?user=postgres"
        }
        generator.apply {
          name = "org.jooq.codegen.KotlinGenerator"
          target.apply {
            packageName = "org.bug"
          }
          database.apply {
            inputSchema = "public"
          }
        }
      }
    }
  }
}

dependencies {
  implementation("org.mapstruct:mapstruct:1.4.2.Final")
  jooqGenerator("org.postgresql:postgresql:42.2.19")
  kapt("org.mapstruct:mapstruct-processor:1.4.2.Final")
}


tasks.named<nu.studer.gradle.jooq.JooqGenerate>("generateJooq") {
  var server: io.zonky.test.db.postgres.embedded.EmbeddedPostgres? = null
  doFirst {
    server = io.zonky.test.db.postgres.embedded.EmbeddedPostgres.builder().setPort(55555).start()
    server!!.postgresDatabase.connection.use {
      it.prepareStatement("CREATE TABLE test (id int primary key) ").execute()
    }
  }
  allInputsDeclared.set(true)
  outputs.cacheIf { true }
  doLast {
    server!!.close()
  }
}

tasks.named("build") {
  dependsOn("generateJooq")
}
```

**Comment by etiennestuder** [comment] 2021-04-19 03:53
Thanks, @NikolayMetchev. I will take a look, but it will take me a moment to find time for it.

**Comment by etiennestuder** [comment] 2021-04-23 07:30
I was able to reproduce the issue, as can be seen in this build scan:
https://scans.gradle.com/s/kgs7vajp6ki6e/deprecations?expanded=WyIzIl0#0

The self-contained example can be found here:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/es/issue-170/example/problem-report/build.gradle.kts

**Comment by etiennestuder** [comment] 2021-04-26 07:47
@NikolayMetchev After some investigation, this turns out to be an issue with the kapt plugin. See this simple example that shows the same behavior in the absence of the gradle-jooq-plugin:
https://github.com/runningcode/kapt-optimizations/blob/master/lib/build.gradle.kts

This build scan shows the lost task dependencies in kaptGenerateStubsKotlin and kaptKotlin:
https://scans.gradle.com/s/fzrijhpwd5gio/console-log#L5

We will raise this with JetBrains. //cc @runningcode

**Comment by NikolayMetchev** [comment] 2021-04-27 07:04
Can you cc me if you create a youtrack issue?

**Comment by NikolayMetchev** [comment] 2021-04-27 07:05
Or just post the link here

**Comment by etiennestuder** [comment] 2021-04-27 07:44
Yes, I will add a link here and then close this issue #170 since there is nothing to be done in the gradle-jooq-plugin.

**Comment by etiennestuder** [comment] 2021-04-27 14:03
See https://youtrack.jetbrains.com/issue/KT-46353

**Closed by etiennestuder** 2021-04-27 14:03 UTC

**Comment by etiennestuder** [comment] 2021-04-29 04:40
@NikolayMetchev Fixed by JB by now. Thanks for having reported this.
