### ISSUE TITLE
<globalTableReferences/> seems to be set to false by default

### ISSUE THREAD

**Issue by lukaseder** [etiennestuder/gradle-jooq-plugin#9] opened 2015-10-26 15:13 UTC
In a discussion with a user of the gradle-jooq-plugin, an interesting observation could be made. Apparently, the generated `Tables.java` class, which holds convenience references to all the generated table literals, is not generated. This could be due to the gradle-jooq-plugin setting the wrong default values for jOOQ code generation configuration flags...?

http://www.jooq.org/doc/latest/manual/getting-started/tutorials/jooq-in-7-steps/jooq-in-7-steps-step5/#comment-2327453126

The default in `org.jooq.util.jaxb.Generate` is:

``` java
    @XmlElement(defaultValue = "true")
    protected Boolean globalTableReferences = true;
```

Could it be that this is `false` by default?

**Comment by etiennestuder** [comment] 2015-10-26 20:28
The plugin is not setting any explicit values. My understanding is that org.jooq.util.GenerationTool#run will create an instance of Generate if it is null (which is the case if no specific config has been done in the jOOQ plugin to configure the Generate element).

**Comment by lukaseder** [comment] 2015-10-26 21:04
Hmm, Ok. This might as well be a user error, then...

Feel free to reject this issue

**Comment by etiennestuder** [comment] 2016-10-30 15:08
Closing as this is most likely a user error. Also, we are successfully seeing the generated `Tables` class in one of our projects that is using jOOQ.

**Comment by lukaseder** [comment] 2017-02-17 09:51
For the record, here's another report of this incident on the mailing list:
https://groups.google.com/d/msg/jooq-user/dpY5azdTCqM/SBP2CC9oEQAJ

I've looked through your code, and it appears that you're not filling the jOOQ `Configuration` object with the proper defaults

**Comment by lukaseder** [comment] 2017-02-17 09:56
For the record, here's another report of this incident on the mailing list:
https://groups.google.com/d/msg/jooq-user/dpY5azdTCqM/SBP2CC9oEQAJ

I've looked through your code, and it appears that you're not filling the jOOQ `Configuration` object with the proper defaults:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/src/main/groovy/nu/studer/gradle/util/JaxbConfigurationBridge.groovy#L66

Your comment there indicates that:

> if the return value is null, create a new instance of the defined return type and set via bean setter method

The XJC-generated `Configuration` class uses `java.lang.Boolean` instead of `boolean` because it is an optional element in the [XSD specification](https://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd)

```xml
<element name="globalTableReferences" type="boolean" default="true" minOccurs="0" maxOccurs="1"/>
```

The default is applied when unmarshalling a missing element, although from my understanding, this is not a requirement. In any case, the jOOQ code generator behaves like this:

- If such a value is `true` or `false`, then that value is assumed to have been explicitly set by the user and is retained
- If such a value is `null`, then that value is assumed to have been omitted, and the default (as specified in the XSD and on the `@XMLElement` annotation) is used.

I think that your plugin should fix this, as it is quite confusing for users when they have to specify all sorts of flags that aren't needed with:

- The standalone generator
- The Maven plugin

Hope this helps

**Comment by etiennestuder** [comment] 2017-03-03 10:13
@lukaseder I cannot reproduce this issue. Default values are properly marshaled to the jOOQ config xml. See [here](https://github.com/etiennestuder/gradle-jooq-plugin/blob/09e572b99cf75ddec3de3a6d148d16bc79790022/src/test/groovy/nu/studer/gradle/jooq/JooqFuncTest.groovy#L112-L114).

**Closed** 2017-03-03 10:14 UTC
