### ISSUE TITLE
Not working when using liquibase codegen with relativeToChangelogFile="false".

### ISSUE THREAD

**Issue by mshima** [etiennestuder/gradle-jooq-plugin#138] opened 2020-08-27 17:31 UTC
Not sure if this should be reported here, but this plugin is failing with the following error:
```
14:12:58.031 [main] ERROR org.jooq.codegen.GenerationTool - Cannot read /Users/mshima/apps/jooq-gradle/build/tmp/generateJooq/config.xml. Error : Error while exporting schema
org.jooq.exception.DataAccessException: Error while exporting schema
        at org.jooq.meta.extensions.AbstractInterpretingDatabase.connection(AbstractInterpretingDatabase.java:103)
        at org.jooq.meta.extensions.AbstractInterpretingDatabase.create0(AbstractInterpretingDatabase.java:77)
        at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:274)
        at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:263)
        at org.jooq.meta.AbstractDatabase.setConnection(AbstractDatabase.java:253)
        at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:521)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:222)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:217)
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:189)
Caused by: liquibase.exception.ChangeLogParseException: liquibase.exception.SetupException: config/liquibase/changelog/00000000000000_initial_schema.xml does not exist
        at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:25)
        at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:217)
        at liquibase.Liquibase.update(Liquibase.java:190)
        at liquibase.Liquibase.update(Liquibase.java:179)
        at liquibase.Liquibase.update(Liquibase.java:175)
        at liquibase.Liquibase.update(Liquibase.java:168)
        at org.jooq.meta.extensions.liquibase.LiquibaseDatabase.export(LiquibaseDatabase.java:156)
        at org.jooq.meta.extensions.AbstractInterpretingDatabase.connection(AbstractInterpretingDatabase.java:100)
        ... 8 common frames omitted
Caused by: liquibase.exception.SetupException: config/liquibase/changelog/00000000000000_initial_schema.xml does not exist
        at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:356)
        at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:305)
        at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23)
        ... 15 common frames omitted
Caused by: liquibase.exception.ChangeLogParseException: config/liquibase/changelog/00000000000000_initial_schema.xml does not exist
        at liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:106)
        at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:15)
        at liquibase.changelog.DatabaseChangeLog.include(DatabaseChangeLog.java:565)
        at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:348)
        ... 17 common frames omitted
```

If I manually change the file path to include `src/main/resources/` it works.

This project can reproduce it:
https://github.com/mshima/jhipster-jooq-gradle-sample

You can see a full debug here:
https://github.com/jhipster/generator-jhipster-jooq/runs/1037869102?check_suite_focus=true

**Comment by lukaseder** [comment] 2020-08-27 19:08
Just to be sure, @etiennestuder, is the `src/main/resources` content on the classpath by default, when invoking `GenerationTool`?

**Comment by etiennestuder** [comment] 2020-08-28 03:25
@lukaseder 

> Just to be sure, @etiennestuder, is the `src/main/resources` content on the classpath by default, when invoking `GenerationTool`?

It is not. By default, only the jOOQ libraries are on the classpath. Both the sql driver as well as any other project-specific resources / libraries required to properly run the GenerationTool need to be added explicitly:
https://github.com/etiennestuder/gradle-jooq-plugin#adding-the-database-driver

I will close this issue since it is not a plugin issue but a usage issue.

**Closed by etiennestuder** 2020-08-28 03:25 UTC

**Comment by lukaseder** [comment] 2020-08-28 06:45
Perfect, thanks for your help, @etiennestuder

**Comment by mshima** [comment] 2020-08-28 16:01
@etiennestuder thanks for your feedback.
I think the issue is a little bit different.

When I tried:
```
jooqGenerator "org.jooq:jooq-meta-extensions:3.13.4"
jooqGenerator file("src/main/resources")
```

I got:
```
A problem occurred evaluating root project 'jhipster'.
> Cannot convert the provided notation to an object of type Dependency: /Users/mshima/aplicacoes/jooq-gradle/src/main/resources.
  The following types/formats are supported:
    - Instances of Dependency.
    - String or CharSequence values, for example 'org.gradle:gradle-core:1.0'.
    - Maps, for example [group: 'org.gradle', name: 'gradle-core', version: '1.0'].
    - FileCollections, for example files('some.jar', 'someOther.jar').
    - Projects, for example project(':some:project:path').
    - ClassPathNotation, for example gradleApi().
```

I have no clue how to proceed from here.
I will try to run using GenerationTool instead.

**Comment by etiennestuder** [comment] 2020-08-29 03:42
@mshima If you read the error message returned by Gradle carefully, you will see that what you wrote is not valid:
`jooqGenerator file("src/main/resources")` should be `jooqGenerator files("src/main/resources")`

From how I understand jOOQ's LiquibaseDatabase class looking at [this code](https://github.com/jOOQ/jOOQ/blob/main/jOOQ-meta-extensions-liquibase/src/main/java/org/jooq/meta/extensions/liquibase/LiquibaseDatabase.java#L145-L153
), you can use file system resources or classpath resources. @lukaseder can maybe confirm this.

If you configure the `scripts` property to be a file system path, just add that path to the jOOQ configuration of the gradle-jooq-plugin. You can see a working example [here](https://github.com/etiennestuder/gradle-jooq-plugin/blob/cd4bd7c36a57dc574462c40d0d6049432bc155b1/src/test/groovy/nu/studer/gradle/jooq/JooqFuncTest.groovy#L945-L953).

If you configure the `scripts` property to be a classpath resource, add it to the `jooqGenerator` configuration as explained above.

**Comment by mshima** [comment] 2020-08-29 04:58
> @mshima If you read the error message returned by Gradle carefully, you will see that what you wrote is not valid:
> `jooqGenerator file("src/main/resources")` should be `jooqGenerator files("src/main/resources")`

In my initial test adding `jooqGenerator files("src/main/resources")` fixed the issue, I will do more tests tomorrow.

> From how I understand jOOQ's LiquibaseDatabase class looking at [this code](https://github.com/jOOQ/jOOQ/blob/main/jOOQ-meta-extensions-liquibase/src/main/java/org/jooq/meta/extensions/liquibase/LiquibaseDatabase.java#L145-L153), you can use file system resources or classpath resources. @lukaseder can maybe confirm this.
>
> If you configure the `scripts` property to be a file system path, just add that path to the jOOQ configuration of the gradle-jooq-plugin. You can see a working example [here](https://github.com/etiennestuder/gradle-jooq-plugin/blob/cd4bd7c36a57dc574462c40d0d6049432bc155b1/src/test/groovy/nu/studer/gradle/jooq/JooqFuncTest.groovy#L945-L953).
> 
> If you configure the `scripts` property to be a classpath resource, add it to the `jooqGenerator` configuration as explained above.

Yep, that's right.

The master.xml script was loading correctly. [master.xml reference](https://github.com/mshima/jhipster-jooq-gradle-sample/blob/e3d13474c01439c84079e6164f8d7c777ba789c3/build.gradle#L328-L331)

The error happens when the root script (master.xml) tries to load the others xmls:
In this case `config/liquibase/changelog/00000000000000_initial_schema.xml` [00000000000000_initial_schema.xml reference](https://github.com/mshima/jhipster-jooq-gradle-sample/blob/e3d13474c01439c84079e6164f8d7c777ba789c3/src/main/resources/config/liquibase/master.xml#L16)

That's the reason we need to add `src/main/resources` to the classpath, otherwise `config/liquibase/changelogs/*` cannot be found.

@etiennestuder thanks for your help.

**Comment by lukaseder** [comment] 2020-08-31 11:35
> From how I understand jOOQ's LiquibaseDatabase class looking at [this code](https://github.com/jOOQ/jOOQ/blob/main/jOOQ-meta-extensions-liquibase/src/main/java/org/jooq/meta/extensions/liquibase/LiquibaseDatabase.java#L145-L153), you can use file system resources or classpath resources. @lukaseder can maybe confirm this.

Confirmed.
