### ISSUE TITLE
Warnings with 2.0.6

### ISSUE THREAD

**Issue by aram535** [etiennestuder/gradle-jooq-plugin#44] opened 2017-05-04 11:28 UTC
Upgraded my plugin fr 2.0.4 to 2.0.6  (jooq 3.9.1 & 3.9.2 both tested)

:generateAPJooq
SchemaSourceMay 04, 2017 7:24:30 AM org.jooq.tools.JooqLogger info
INFO: Initialising properties  : E:\src\ap\build\tmp\jooq\config.xml
May 04, 2017 7:24:30 AM org.jooq.tools.JooqLogger warn
WARNING: Unmarshal warning        : cvc-complex-type.2.4.a: Invalid content was found starting with element 'varargSetters'. One of '{"http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd":fullyQualifiedTypes, "http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd":emptyCatalogs, "http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd":emptySchemas, "http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd":javaTimeTypes}' is expected.
May 04, 2017 7:24:30 AM org.jooq.tools.JooqLogger warn
WARNING: Unmarshal warning        : unexpected element (uri:"http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd", local:"varargSetters"). Expected elements are <{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}queues>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}fluentSetters>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}globalSequenceReferences>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}pojos>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}pojosEqualsAndHashCode>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}globalTableReferences>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}springAnnotations>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}javaTimeTypes>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}relations>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}routines>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}udts>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}immutablePojos>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}globalQueueReferences>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}emptySchemas>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}interfaces>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}validationAnnotations>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}globalUDTReferences>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}immutableInterfaces>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}instanceFields>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}pojosToString>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}tables>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}globalRoutineReferences>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}links>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}globalLinkReferences>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}deprecated>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}jpaAnnotations>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}records>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}fullyQualifiedTypes>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}globalCatalogReferences>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}daos>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}generatedAnnotation>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}emptyCatalogs>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}globalObjectReferences>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}sequences>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}globalSchemaReferences>

**Comment by aram535** [comment] 2017-05-04 12:14
The diff for the generated config.xml is:

+   xmlns='http://www.jooq.org/xsd/jooq-codegen-3.9.2.xsd'
-   xmlns='http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd'

+       <varargSetters>true</varargSetters>

**Comment by risbarov** [comment] 2017-05-04 12:26
Same problem with 2.0.6 (and JOOQ 3.9.2) :-(
Here is my config:

```
jooq {
    db(sourceSets.main) {
        jdbc {
            driver = project.getProperty('db.driver')
            url = project.getProperty('db.url')
            user = project.getProperty('db.username')
            password = project.getProperty('db.password')
        }
        generator {
            name = 'org.jooq.util.DefaultGenerator'
            strategy {
                name = 'org.jooq.util.DefaultGeneratorStrategy'
            }
            database {
                name = 'org.jooq.util.postgres.PostgresDatabase'
                inputSchema = project.getProperty('db.schema')
            }
            generate {
                javaTimeTypes = true
            }
            target {
                packageName = 'my.test'
            }
        }
    }
}
```
Output:
```
WARNING: Unmarshal warning        : cvc-complex-type.2.4.a: Invalid content was found starting with element 'varargSetters'. One of '{"http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd":fullyQualifiedTypes, "http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd":emptyCatalogs, "http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd":emptySchemas, "http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd":javaTimeTypes}' is expected.
May 04, 2017 3:24:44 PM org.jooq.tools.JooqLogger warn
WARNING: Unmarshal warning        : unexpected element (uri:"http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd", local:"varargSetters"). Expected elements are <{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}queues>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}fluentSetters>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}globalSequenceReferences>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}pojos>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}pojosEqualsAndHashCode>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}globalTableReferences>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}springAnnotations>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}javaTimeTypes>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}relations>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}routines>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}udts>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}immutablePojos>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}globalQueueReferences>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}emptySchemas>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}interfaces>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}validationAnnotations>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}globalUDTReferences>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}immutableInterfaces>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}instanceFields>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}pojosToString>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}tables>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}globalRoutineReferences>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}links>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}globalLinkReferences>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}deprecated>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}jpaAnnotations>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}records>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}fullyQualifiedTypes>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}globalCatalogReferences>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}daos>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}generatedAnnotation>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}emptyCatalogs>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}globalObjectReferences>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}sequences>,<{http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd}globalSchemaReferences>
```

**Comment by lukaseder** [comment] 2017-05-04 12:33
In jOOQ 3.9.2, the XSD was upgraded from 3.9.0 to 3.9.2 to support this new `varargSetters` flag. The jOOQ `org.jooq.Constants.XSD_CODEGEN` correctly references this new version:
https://github.com/jOOQ/jOOQ/blob/version-3.9.2/jOOQ/src/main/java/org/jooq/Constants.java#L104

Perhaps this plugin doesn't pull the correct jOOQ version yet?

**Comment by etiennestuder** [comment] 2017-05-04 12:59
@aram535 Please set the version 3.9.2 explicitly in the DSL:

```
jooq {
    version = '3.9.2'
    ...
```

I missed to set the default version to 3.9.2 in the plugin 2.0.6.

**Comment by risbarov** [comment] 2017-05-04 13:07
@etiennestuder setting version explicitly didn't help me. In the build log I see the following:

```
May 04, 2017 3:59:39 PM org.jooq.tools.JooqLogger info
INFO: 
                                      
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@  @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@
@@@@@@@@@@@@@@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@  @@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@        @@  @  @  @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  Thank you for using jOOQ 3.9.1
```

Gradle uses JOOQ 3.9.1.

Let's look at project dependencies:

```
jooqRuntime - The classpath used to invoke the jOOQ generator. Add your JDBC drivers or generator extensions here.
+--- org.jooq:jooq-codegen: -> 3.9.1
|    +--- org.jooq:jooq:3.9.1
|    \--- org.jooq:jooq-meta:3.9.1
|         \--- org.jooq:jooq:3.9.1
\--- org.postgresql:postgresql:42.0.0
```

**Comment by etiennestuder** [comment] 2017-05-04 13:34
I cannot reproduce this. I have two projects where this works as expected:

```
jooqRuntime - The classpath used to invoke the jOOQ generator. Add your JDBC drivers or generator extensions here.
+--- org.jooq:jooq-codegen: -> 3.9.2
|    +--- org.jooq:jooq:3.9.2
|    \--- org.jooq:jooq-meta:3.9.2
|         \--- org.jooq:jooq:3.9.2
\--- org.postgresql:postgresql:9.4.1212
```

**Comment by etiennestuder** [comment] 2017-05-04 13:39
Please run the sample in https://github.com/etiennestuder/gradle-jooq-plugin/tree/master/example/remove_task_dependency (invoke `./gradlew generateSampleJooqSchemaSource`) and let me know if you do not see jOOQ 3.9.2 applied (I do see 3.9.2 as expected).

**Comment by aram535** [comment] 2017-05-04 13:52
Must be a daemon or cache issue, because if I pull my repo to a new machine it doesn't pop the warning.

**Comment by etiennestuder** [comment] 2017-05-04 15:46
Interesting. I suggest you delete the .gradle folder in the root of your project and try again.

**Comment by etiennestuder** [comment] 2017-05-04 15:47
I'll close this issue since there is nothing wrong on the plugin side. (a fix to the default jOOQ version is already in master) Thanks for reporting this issue, @aram535 !

**Closed by etiennestuder** 2017-05-04 15:47 UTC
