### ISSUE TITLE
Version mismatch when using gradle-jooq-plugin with Spring Boot 1

### ISSUE THREAD

**Issue by jbarop** [etiennestuder/gradle-jooq-plugin#81] opened 2018-07-23 14:13 UTC
Hello,

I've ran in an issue today when I was trying to use gradle-jooq-plugin-3.0.1 with jooq-3.11.2 with Spring Boot 1.

```gradle
plugins {
  id 'nu.studer.jooq' version '3.0.1'
  id 'org.springframework.boot' version '1.5.14.RELEASE' // References jooq-3.9.6
  id 'java'
}

repositories {
  mavenCentral()
}

dependencies {
  jooqRuntime 'com.h2database:h2:1.4.177'
  compile 'org.jooq:jooq'
}

bootRepackage.enabled = false

jooq {
  version = '3.11.2' // This is silently ignored

  sample(sourceSets.main) {
    jdbc {
      driver = 'org.h2.Driver'
      url = 'jdbc:h2:~/test-gradle'
      user = 'sa'
      password = ''
    }
    generator {
      database {}
      target {
        packageName = 'org.jooq.example.gradle.db'
      }
    }
  }

}
```

The build will fail with `Error: Could not find or load main class org.jooq.codegen.GenerationTool`. After inspecting the classpath I noticed that jooq-3.9.6, which is defined in Spring Boot, is used. The version from the plugin configuration is ignored.

Workaround: Specify/Override the version set by Spring Boot like so:
```
ext['jooq.version'] = '3.11.2'
```

The plugin could that automatically or do a check and exit with an error message.

**Comment by cocoon1274** [comment] 2018-07-28 08:30
Thank you for your sharing. It was my first time to set up the project with jooq-gradle-plugin. And I was totally confused about this problem. I was able to solve this problem. Again, I really appreciate your help. God bless you👍

**Comment by etiennestuder** [comment] 2018-09-03 08:27
Closing this issue as the behavior is understood (and it's not a bug in the gradle jooq plugin) and a workaround is described in the README.

**Closed by etiennestuder** 2018-09-03 08:27 UTC

**Comment by etiennestuder** [comment] 2018-09-03 08:42
@jbarop @cocoon1274 You can also swap this from 

```
id 'nu.studer.jooq' version '3.0.1'
id 'org.springframework.boot' version '1.5.14.RELEASE' // References jooq-3.9.6
```

to

```
id 'org.springframework.boot' version '1.5.14.RELEASE' // References jooq-3.9.6
id 'nu.studer.jooq' version '3.0.1'
```

to make this work properly.

**Comment by marceloverdijk** [comment] 2019-10-20 18:04
Or use:

```
plugins {
  id "java"
  id "io.spring.dependency-management" version "1.0.8.RELEASE"
  id "nu.studer.jooq" version "3.0.3" // Uses jOOQ 3.11.11
  id "org.springframework.boot" version "2.2.0.RELEASE" // Uses jOOQ 3.12.1
}

jooq {
  version = dependencyManagement.importedProperties["jooq.version"] // Will make sure jOOQ 3.12.1 is used
}
```

**Comment by FyiurAmron** [comment] 2025-01-07 14:27
@marceloverdijk IIUC, you can just do `version = ""` - the plugin will then add a dep specifier that has empty version string, so Gradle will then use the version from whatever platform or other dep source you provide. It also works without Spring Dependency Management.
